### ISSUE TITLE
@:forward() for abstracts

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/dox#87]
Looks like `@:forward()` meta for abstract types is currently not supported.
http://haxe.org/manual/types-abstract-forward.html

**Comment by nightblade9** [comment]
I ran into this today and would like a fix. Are there any updates on this issue (from three years ago)? This is really a problem because, in my case ([sample gist here](https://gist.githubusercontent.com/bsinky/3c79fd029af35f5db55506d8be6bd9f0/raw/3a60c6a6e9ddac7077243655f3b7c4265c102963/Dictionary.hx)) I can't simply write docs on non-existent methods in the non-abstract type.

**Comment by jgranick** [comment]
We're having the same issue.

We use abstracts to support OpenGL ES 3.0, OpenGL ES 2.0, WebGL 2 and WebGL contexts. The abstracts use `@:forward()` to limit the properties and methods that are available (without having to retype them all, there are a lot!

This page (especially) is disappointing:

http://api.lime.software/lime/graphics/OpenGLES2RenderContext.html

Supporting "Inherited Variables" and "Inherited Methods" would be a reasonable way to handle this probably

**Comment by markknol** [comment]
@Simn is this a Haxe or a dox issue?

**Comment by Simn** [comment]
Dox

**Comment by sebthom** [comment]
@Simn I think you can close this issue now.
